### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by InT0xicaTI0n** [griffenx/Apex-Launcher#8] opened 2017-01-19 20:01 UTC
![game not found](https://cloud.githubusercontent.com/assets/25231953/22122999/e10f61ce-de81-11e6-9584-fb5f77c9beaf.PNG)
![handling error](https://cloud.githubusercontent.com/assets/25231953/22123001/e35d6ade-de81-11e6-892a-260dd9227cfd.PNG)

**Hi there! I have recently installed Pokémon Apex Alpha 5.2 and after downloading the update (bearing in mind I had played this game a long time ago and it worked fine), it first came up with the message shown on the picture and then when I pressed yes to it, it appeared with the second image and the details listed here:** 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.Net.WebClient.GetUri(String path)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Apex_Launcher.Program.DownloadVersion(Version v)
   at Apex_Launcher.Launcher.LaunchButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Apex Launcher
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Users/toxic/Desktop/Apex.Launcher.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Bearing in mind that I never had any problems with game before these two issues, I will appreciate any help you offer as I am nowhere near a computer wiz :)
Thank you!**

**Comment by griffenx** [comment] 2017-01-19 20:05
This error is caused by the fact that (starting with Build 5.1) I introduced a patching system to allow me to release patches to fix bugs without forcing people to download the entire game each time (which is pretty big with all the music). Before v1.3.0, patches weren't supported by the Launcher, so I had to add functionality for them. Try using version 1.3.0 of the launcher and see if that works.

**Comment by InT0xicaTI0n** [comment] 2017-01-19 20:07
I just tried that and I got the same message

**Comment by InT0xicaTI0n** [comment] 2017-01-19 20:09
Shall I go and download the whole game again?

**Comment by griffenx** [comment] 2017-01-19 20:20
Two things:
1. Make sure you're using the .exe that was listed under v1.3.0 on the Releases page.
2. Check to see what the error details are. If you're using v1.3.0, it should give you a different error. This version doesn't use the DownloadFile() method that you see in the exception text from the old version.

If you did get a different error, can you copy the Exception Text portion of it for me?

**Comment by InT0xicaTI0n** [comment] 2017-01-19 20:26
Nope. I still get the same error and the file I was used was defiantly the exe. file.

**Comment by InT0xicaTI0n** [comment] 2017-01-19 20:26
I'm really sorry about this. Its probably me doing something wrong

**Comment by griffenx** [comment] 2017-01-19 20:30
Can you provide the "Exception Text" part of the error it's now giving you? That'll give me the details.

**Comment by InT0xicaTI0n** [comment] 2017-01-19 20:31
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.Net.WebClient.GetUri(String path)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Apex_Launcher.Program.DownloadVersion(Version v)
   at Apex_Launcher.Launcher.LaunchButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by griffenx** [comment] 2017-01-19 20:42
I'm confident that you're not using the correct version of the launcher. See these lines:

> at System.Net.WebClient.DownloadFile(String address, String fileName)
at Apex_Launcher.Program.DownloadVersion(Version v)

That means that my method `DownloadVersion()` is calling the system method `DownloadFile()`, however this hasn't been the case for many versions. The current version of the `DownloadVersion()` method looks like this:

    public static void DownloadVersion(Version v) {
            DownloadForm dlf = new DownloadForm(v);
            dlf.Show();
            dlf.StartDownload();

            //wc.DownloadFile(v.Location, filename + ".zip");
        }

That last line before the closing brace is commented out (the `//` mark). This means that the line is ignored when the program is run. This line has been disabled since v1.1.0.

Essentially, it should be impossible for v1.3.0 to generate this exception. Try deleting whatever version of the launcher you currently have installed and try downloading v1.3.0 again and make sure you're launching that .exe file.

**Comment by InT0xicaTI0n** [comment] 2017-01-19 20:44
Ok

**Comment by griffenx** [comment] 2017-01-20 13:01
Can you let me know if this has resolved the issue?

**Comment by griffenx** [comment] 2017-01-22 01:13
I haven't heard back in over two days, so I'm going to assume that this issue has been solved. If it is still persisting (and you believe the issue is something other than what we've discussed), please reopen the report.

**Closed by griffenx** 2017-01-22 01:13 UTC
