### ISSUE TITLE
Pokemon Apex

### ISSUE THREAD

**Issue by Br0me** [griffenx/Apex-Launcher#26] opened 2019-03-05 19:47 UTC
# Exception Details
System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\WINDOWS\system32\config.txt" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   bei System.IO.FileStream..ctor(String path, FileMode mode)
   bei Apex_Launcher.Program.initialize()
   bei Apex_Launcher.Program.Main()

# Configuration
* Current Launcher Version: 1.4.3.0

# Files

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0

**Comment by griffenx** [comment] 2019-03-05 20:11
This is a duplicate of #25, please include any additional information in that thread.

**Closed by griffenx** 2019-03-05 20:11 UTC
