### ISSUE TITLE
launcher not showing the launch game option

### ISSUE THREAD

**Issue by weeb-destroyer** [griffenx/Apex-Launcher#28] opened 2019-03-27 22:50 UTC

**Comment by griffenx** [comment] 2019-03-28 15:10
I believe this should be fixed as of the latest commit. Please test the updated build of the launcher below and confirm if the issue is resolved.
[Apex Launcher.zip](https://github.com/griffenx/Apex-Launcher/files/3018645/Apex.Launcher.zip)

**Comment by griffenx** [comment] 2019-03-29 14:24
Additional testers have confirmed that this issue has been resolved in v1.4.5

**Closed by griffenx** 2019-03-29 14:24 UTC
Labels: Awaiting Information, In-Progress
