### ISSUE TITLE
Crash During Version Extract

### ISSUE THREAD

**Issue by Garchomp75** [griffenx/Apex-Launcher#14] opened 2017-05-16 14:41 UTC
hey so i tried downloading the game thrice now, twice through the .exe and once through manual. The .exe stopped working as soon as the game started extracting. Other 2 times it failed to download the game. Idk why because my internet is very fast.

**Comment by Garchomp75** [comment] 2017-05-16 14:47
So it's simple I opened the client and I started downloading the game. After downloading it said "extracting game" and when this happens my clients crashes saying it has stopped working. I have tried downloading manually too but that also failed midway. Other games download fine

**Comment by griffenx** [comment] 2017-05-16 14:50
That's not what I'm asking. When the application crashes, it shows a dialog box that asks if you want to close the application. There is a button at the bottom of that dialog that says "View problem details."

I need you to click that button. It will display a large block of text that will include specific technical details about what went wrong. I need you to provide me that text.

**Comment by Garchomp75** [comment] 2017-05-16 16:11
these are the error details

 Problem Event Name:	CLR20r3
  Problem Signature 01:	Apex.Launcher.exe
  Problem Signature 02:	1.4.0.0
  Problem Signature 03:	588403c0
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.36366
  Problem Signature 06:	57a0f7f9
  Problem Signature 07:	4528
  Problem Signature 08:	19d
  Problem Signature 09:	System.IO.IOException
  OS Version:	6.3.9600.2.0.0.768.100
  Locale ID:	1033
  Additional Information 1:	ea01
  Additional Information 2:	ea01121c3aac7fcaf31ec565686aff41
  Additional Information 3:	dc87
  Additional Information 4:	dc8703169ee5de075160dc4dda27e9e9

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by griffenx** [comment] 2017-05-16 16:15
Thank you. It looks like there is an issue accessing a file or directory on your computer at the point when the problem occurs. Can you take a look in the folder where the `.exe` for the Launcher is located and see if a subfolder called `Versions` exists? If so, could you list for me the contents of that subfolder? Feel free to omit `VersionManifest.xml`.

**Comment by Garchomp75** [comment] 2017-05-16 16:24
it has an alpha 6 folder with all the audio in it and an alpha 6 zip file

**Comment by griffenx** [comment] 2017-05-16 16:28
Is it just the audio? What happens if you try to extract the `.zip` file manually?

**Comment by Garchomp75** [comment] 2017-05-16 16:44
So I extracted the game and it works. I extracted it and replaced the files in the folder. However the game still can't be played through the client. I can play it by running the game in the versions folder

**Comment by Garchomp75** [comment] 2017-05-16 16:48
The game saves as well. Now my only concern is that without the client I can't update the game later

**Comment by griffenx** [comment] 2017-05-16 17:22
You can manually download updates, however I'd like to get this issue resolved so that we don't have to deal with it again.

Let's try to narrow down exactly when the error occurs. Did it look like the program was able to extract all of the files from the `.zip`? You mentioned that the audio files were there. Were there any other files as well?

Hopefully we'll be able to tell if this error is occurring either during or after the extraction process.

Another question: did you modify the Install Path variable in the Launcher's settings or move any of the associated files? Doing any of these have been known to cause issues in the current version.

**Comment by Garchomp75** [comment] 2017-05-16 17:45
So the error occurs during extraction. The client crashes while extracting music files or after extracting music files. There are only music files that are extracted through the client. However I was able to manually extract the game From the zip file. Also I didn't change any paths or modify settings

**Comment by griffenx** [comment] 2017-05-16 18:02
Alright, so that narrows it down quite nicely. I'll look into this when I get home and let you know what I find.

**Comment by griffenx** [comment] 2017-05-16 23:42
Alright, so the part of the code in question only throws this kind of exception under the following circumstances:

1. If the folder it's trying to extract to already exists. This shouldn't be the case, as there's an explicit call to delete said folder if it exists before extracting is attempted.
2. If any of the contents of the archive have an invalid name. This shouldn't be the case, as you were able to extract the archive fine when doing so manually.
3. If a duplicate file is extracted. See above.

This leads me to believe that the actual exception is being thrown by something called by this method. However, without a proper stack trace, I can't really very effectively diagnose the issue. I am currently working on a new feature for the Launcher that will allow people to easily post error messages if they occur. I'm hoping to have this new version out tonight, so we can try this again with the new feature.

**Comment by Garchomp75** [comment] 2017-05-17 03:12
Okay

**Comment by Garchomp75** [comment] 2017-05-17 13:12
So I figured one of the issues. If you go to > versions> alpha 6(rename it to alpha 0) and you can launch the game through client. However I don't think you'll be able to update the game. If you click update then it'll download 688mb again. I don't know if that's how it's supposed to update or it's redownloading.

**Comment by griffenx** [comment] 2017-05-20 15:59
I've released a new version of the launcher that contains a built-in error reporter. Can you try reproducing this issue in the new version?

**Comment by griffenx** [comment] 2017-05-27 04:35
Since no information has been provided, I'm closing this issue.

**Closed by griffenx** 2017-05-27 04:35 UTC
Labels: Awaiting Information, In-Progress
